on:
  workflow_call:
    secrets:
      GH_TOKEN:
        required: true

jobs:
  go-build:
    runs-on: ubuntu-latest
    steps:
      -
        name: checkout
        uses: actions/checkout@v4
      -
        id: config
        name: load env config
        uses: gertd/yaml-reader-action@v1.0
        with:
          file: .github/env.yaml        
      -
        name: print env
        run: |
          echo "VAULT_ADDR: ${{ steps.config.outputs.VAULT_ADDR }}"
          echo "GO_VERSION: ${{ steps.config.outputs.GO_VERSION }}"
          echo "GO_RELEASER_VERSION: ${{ steps.config.outputs.GO_RELEASER_VERSION }}"
          echo "GO_LANGCI_LINT_VERSION: ${{ steps.config.outputs.GO_LANGCI_LINT_VERSION }}"
          echo "GO_TESTSUM_VERSION: ${{ steps.config.outputs.GO_TESTSUM_VERSION }}"
      -
        name: setup go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ steps.config.outputs.GO_VERSION }}
      -
        name: build
        uses: goreleaser/goreleaser-action@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          distribution: goreleaser
          version: ${{ steps.config.outputs.GO_RELEASER_VERSION }}
          args: build --clean --snapshot --single-target
      -
        name: lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: ${{ steps.config.outputs.GO_LANGCI_LINT_VERSION }}
          args: --timeout=30m
      -
        name: test setup
        uses: gertd/action-gotestsum@v3.0.0
        with:
          gotestsum_version: ${{ steps.config.outputs.GO_TESTSUM_VERSION }}
      -
        name: test
        run: |
          gotestsum --format short-verbose -- -count=1 -parallel=1 -v -coverprofile=cover.out -coverpkg=./... ./...;
      -
        name: upload code coverage
        uses: shogo82148/actions-goveralls@v1
        continue-on-error: true
        with:
          path-to-profile: cover.out
            