on:
  workflow_call:
    secrets:
      GH_TOKEN:
        required: true

env:
  VAULT_ADDR: https://vault.eng.aserto.com/
  PRE_RELEASE: ${{ github.ref == 'refs/heads/main' && 'main' || '' }}
  GO_VERSION: "1.22"
  GO_RELEASER_VERSION: "v1.24.0"
  GO_LANGCI_LINT_VERSION: "v1.56.2"
  GO_TESTSUM_VERSION: "1.11.0"

jobs:
  go-build:
    runs-on: ubuntu-latest
    steps:
      -
        name: checkout
        uses: actions/checkout@v4
      -
        name: setup go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      -
        name: build
        uses: goreleaser/goreleaser-action@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          distribution: goreleaser
          version: ${{ env.GO_RELEASER_VERSION }}
          args: build --clean --snapshot --single-target
    