on:
  workflow_call:
    secrets:
      GH_TOKEN:
        required: true

jobs:
  go-env: 
    uses: gertd/workflows/.github/workflows/go-env.yaml@main

  go-docker-build:
    runs-on: ubuntu-latest
    needs: go-env

    steps:
      -
        name: checkout
        uses: actions/checkout@v4
      -
        name: print go-env values
        run: |
          echo "GO_VERSION: ${{ needs.go-env.outputs.GO_VERSION }}"
          echo "GO_RELEASER_VERSION: ${{ needs.go-env.outputs.GO_RELEASER_VERSION }}"
          echo "GO_LANGCI_LINT_VERSION: ${{ needs.go-env.outputs.GO_LANGCI_LINT_VERSION }}"
          echo "GO_TESTSUM_VERSION: ${{ needs.go-env.outputs.GO_TESTSUM_VERSION }}"
          echo "SVU_VERSION: ${{ needs.go-env.outputs.SVU_VERSION }}"
          echo "SYFT_VERSION: ${{ needs.go-env.outputs.SYFT_VERSION }}"
      -
        name: setup go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ needs.go-env.outputs.GO_VERSION }}
      -
        name: setup QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: https://ghcr.io
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}
      -
        name: docker SSH setup
        run: |
          mkdir -p $HOME/.ssh
          umask 0077 && echo -e "${SSH_PRIVATE_KEY}" > $HOME/.ssh/id_rsa
          ssh-keyscan github.com >> $HOME/.ssh/known_hosts
          git config --global url."git@github.com:".insteadOf https://github.com/
          git config --global user.email "github-bot@aserto.com"
          git config --global user.name "Aserto Bot"
          eval `ssh-agent`
          ssh-add $HOME/.ssh/id_rsa
      -
        name: release
        uses: goreleaser/goreleaser-action@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          distribution: goreleaser
          version: ${{ needs.go-env.outputs.GO_RELEASER_VERSION }}
          args: --clean --snapshot
