on:
  workflow_call:
    secrets:
      GH_TOKEN:
        required: true

jobs:
  go-env: 
    uses: gertd/workflows/.github/workflows/go-env.yaml@main

  go-release:
    runs-on: ubuntu-latest
    needs: go-env

    steps:
      -
        name: checkout
        uses: actions/checkout@v4
      -
        name: print go-env values
        run: |
          echo "VAULT_ADDR: ${{ needs.go-env.outputs.VAULT_ADDR }}"
          echo "GO_VERSION: ${{ needs.go-env.outputs.GO_VERSION }}"
          echo "GO_RELEASER_VERSION: ${{ needs.go-env.outputs.GO_RELEASER_VERSION }}"
          echo "GO_LANGCI_LINT_VERSION: ${{ needs.go-env.outputs.GO_LANGCI_LINT_VERSION }}"
          echo "GO_TESTSUM_VERSION: ${{ needs.go-env.outputs.GO_TESTSUM_VERSION }}"
